//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth3.Shared.Languages {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth3.Shared.Languages.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AboutWindowCloseButton {
            get {
                return ResourceManager.GetString("AboutWindowCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AllCategoryDisplayName {
            get {
                return ResourceManager.GetString("AllCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (c) 2025 rkttu.com, All rights reserved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This application is released as open source under the Affero GPL v3 license.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppLicense {
            get {
                return ResourceManager.GetString("AppLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TableCloth과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The 식탁보® (TableCloth) trademark is protected by trademark law in the Republic of Korea.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppTrademark {
            get {
                return ResourceManager.GetString("AppTrademark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Banking과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BankingCategoryDisplayName {
            get {
                return ResourceManager.GetString("BankingCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check _Update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CheckUpdateButton {
            get {
                return ResourceManager.GetString("CheckUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Credit Cards과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreditCardCategoryDisplayName {
            get {
                return ResourceManager.GetString("CreditCardCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Education과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EducationCategoryDisplayName {
            get {
                return ResourceManager.GetString("EducationCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Financing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FinancingCategoryDisplayName {
            get {
                return ResourceManager.GetString("FinancingCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/yourtablecloth/TableCloth과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GitHubUrl {
            get {
                return ResourceManager.GetString("GitHubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Government과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GovernmentCategoryDisplayName {
            get {
                return ResourceManager.GetString("GovernmentCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insurance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InsuranceCategoryDisplayName {
            get {
                return ResourceManager.GetString("InsuranceCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Others과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OtherCategoryDisplayName {
            get {
                return ResourceManager.GetString("OtherCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://yourtablecloth.app과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ProjectWebSiteUrl {
            get {
                return ResourceManager.GetString("ProjectWebSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Securities과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SecurityCategoryDisplayName {
            get {
                return ResourceManager.GetString("SecurityCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visit _GitHub과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VisitGitHubButton {
            get {
                return ResourceManager.GetString("VisitGitHubButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visit _Web Site과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VisitWebSiteButton {
            get {
                return ResourceManager.GetString("VisitWebSiteButton", resourceCulture);
            }
        }
    }
}
