//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth3.Spork.Languages {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SporkStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SporkStrings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth3.Spork.Languages.SporkStrings", typeof(SporkStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _About...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Addons과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddonsHeader {
            get {
                return ResourceManager.GetString("AddonsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Catalogs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CatalogHeader {
            get {
                return ResourceManager.GetString("CatalogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChatHeader {
            get {
                return ResourceManager.GetString("ChatHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installing plugins...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InProgressMessage {
            get {
                return ResourceManager.GetString("InProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installing Plugins과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InstallerProgressWindowTitle {
            get {
                return ResourceManager.GetString("InstallerProgressWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a web site to launch: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InstructionLabel {
            get {
                return ResourceManager.GetString("InstructionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LaunchButton {
            get {
                return ResourceManager.GetString("LaunchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No items found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReasonLinkText {
            get {
                return ResourceManager.GetString("ReasonLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type the search keyword here...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SearchBoxWatermark {
            get {
                return ResourceManager.GetString("SearchBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spork과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SporkMainWindowTitle {
            get {
                return ResourceManager.GetString("SporkMainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected Error Occurred: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnexpectedErrorMessage_Arg0 {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage_Arg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected Error Occurred과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnexpectedErrorMessage_Title {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage_Title", resourceCulture);
            }
        }
    }
}
